algoritmo "semnome"
var
   Contador, valor1, valor2, valor3 : inteiro
inicio


      valor1 <- 0
      Escreval(valor1)
      valor2 <- 1
      Escreval(valor2)

      Para Contador <- 3 ate 15 faca



           valor3 <- valor1 + valor2
           Escreval(valor3)
           
           valor1 <- valor2
           valor2 <- valor3
           
           
           
      FimPara




fimalgoritmo
